"""
Type hints stub para InSimApp - Proporciona autocompletado para handlers ISP_*
Este archivo se genera automáticamente desde packets.RECEIVE y packets.SEND
Regenerar con: python src/lfs_insim/generate_stubs.py

Para recibir paquetes: define on_ISP_* methods
Para enviar paquetes: usa self.send_ISP_*(param1=val1, ...) o self.send(ISP_CLASE(...))
"""

from typing import Dict, List, Optional, TYPE_CHECKING, Any
from pathlib import Path
from .insim_client import InSimClient
from .packets import *
from .insim_enums import *

if TYPE_CHECKING:
    from .insim_loader import InSimLoader

class InSimApp(InSimClient):
    dependencies: List[str]
    version: str
    description: str
    
    def __init__(
        self,
        config: Optional[dict] = None,
        name: Optional[str] = None,
        _loader: Optional['InSimLoader'] = None,
        _insim_path: Optional[Path] = None,
    ) -> None: ...
    
    def _load_metadata(self) -> None: ...
    def _resolve_dependencies(self) -> None: ...
    @staticmethod
    def _parse_dep_name(dep_spec: str) -> str: ...
    
    def get_insim(self, name: str) -> Optional['InSimApp']: ...
    def require(self, name: str) -> 'InSimApp': ...
    
    # ===== HANDLERS DE PAQUETES RECIBIDOS (on_ISP_*) =====
    # Estos se llaman automáticamente cuando llega un paquete del tipo correspondiente
    def on_ISP_ACR(self, packet: ISP_ACR) -> None: ...
    def on_ISP_AII(self, packet: ISP_AII) -> None: ...
    def on_ISP_AXI(self, packet: ISP_AXI) -> None: ...
    def on_ISP_AXM(self, packet: ISP_AXM) -> None: ...
    def on_ISP_AXO(self, packet: ISP_AXO) -> None: ...
    def on_ISP_BFN(self, packet: ISP_BFN) -> None: ...
    def on_ISP_BTC(self, packet: ISP_BTC) -> None: ...
    def on_ISP_BTT(self, packet: ISP_BTT) -> None: ...
    def on_ISP_CCH(self, packet: ISP_CCH) -> None: ...
    def on_ISP_CIM(self, packet: ISP_CIM) -> None: ...
    def on_ISP_CNL(self, packet: ISP_CNL) -> None: ...
    def on_ISP_CON(self, packet: ISP_CON) -> None: ...
    def on_ISP_CPP(self, packet: ISP_CPP) -> None: ...
    def on_ISP_CPR(self, packet: ISP_CPR) -> None: ...
    def on_ISP_CRS(self, packet: ISP_CRS) -> None: ...
    def on_ISP_CSC(self, packet: ISP_CSC) -> None: ...
    def on_ISP_FIN(self, packet: ISP_FIN) -> None: ...
    def on_ISP_FLG(self, packet: ISP_FLG) -> None: ...
    def on_ISP_HLV(self, packet: ISP_HLV) -> None: ...
    def on_ISP_III(self, packet: ISP_III) -> None: ...
    def on_ISP_IPB(self, packet: ISP_IPB) -> None: ...
    def on_ISP_ISM(self, packet: ISP_ISM) -> None: ...
    def on_ISP_LAP(self, packet: ISP_LAP) -> None: ...
    def on_ISP_MAL(self, packet: ISP_MAL) -> None: ...
    def on_ISP_MCI(self, packet: ISP_MCI) -> None: ...
    def on_ISP_MSO(self, packet: ISP_MSO) -> None: ...
    def on_ISP_NCI(self, packet: ISP_NCI) -> None: ...
    def on_ISP_NCN(self, packet: ISP_NCN) -> None: ...
    def on_ISP_NLP(self, packet: ISP_NLP) -> None: ...
    def on_ISP_NPL(self, packet: ISP_NPL) -> None: ...
    def on_ISP_OBH(self, packet: ISP_OBH) -> None: ...
    def on_ISP_PEN(self, packet: ISP_PEN) -> None: ...
    def on_ISP_PFL(self, packet: ISP_PFL) -> None: ...
    def on_ISP_PIT(self, packet: ISP_PIT) -> None: ...
    def on_ISP_PLA(self, packet: ISP_PLA) -> None: ...
    def on_ISP_PLH(self, packet: ISP_PLH) -> None: ...
    def on_ISP_PLL(self, packet: ISP_PLL) -> None: ...
    def on_ISP_PLP(self, packet: ISP_PLP) -> None: ...
    def on_ISP_PSF(self, packet: ISP_PSF) -> None: ...
    def on_ISP_REO(self, packet: ISP_REO) -> None: ...
    def on_ISP_RES(self, packet: ISP_RES) -> None: ...
    def on_ISP_RIP(self, packet: ISP_RIP) -> None: ...
    def on_ISP_RST(self, packet: ISP_RST) -> None: ...
    def on_ISP_SLC(self, packet: ISP_SLC) -> None: ...
    def on_ISP_SMALL(self, packet: ISP_SMALL) -> None: ...
    def on_ISP_SPX(self, packet: ISP_SPX) -> None: ...
    def on_ISP_SSH(self, packet: ISP_SSH) -> None: ...
    def on_ISP_STA(self, packet: ISP_STA) -> None: ...
    def on_ISP_TINY(self, packet: ISP_TINY) -> None: ...
    def on_ISP_TOC(self, packet: ISP_TOC) -> None: ...
    def on_ISP_UCO(self, packet: ISP_UCO) -> None: ...
    def on_ISP_VER(self, packet: ISP_VER) -> None: ...
    def on_ISP_VTN(self, packet: ISP_VTN) -> None: ...
    def on_OutGaugePack(self, packet: OutGaugePack) -> None: ...
    def on_OutSimPack(self, packet: OutSimPack) -> None: ...
    def on_OutSimPack2(self, packet: OutSimPack2) -> None: ...

    # ===== MÉTODOS PARA ENVÍO (send_ISP_*) =====
    # Envía un paquete. Ejemplo: self.send_ISP_MST(Msg="Hola")
    def send_ISP_AIC(self, ReqI: int = ..., PLID: int = ..., Inputs: list = ...) -> None: ...
    def send_ISP_AXM(self, ReqI: int = ..., NumO: int = ..., UCID: int = ..., PMOAction: PMO = ..., PMOFlags: PMOF = ..., Sp3: int = ..., Info: list = ...) -> None: ...
    def send_ISP_BFN(self, ReqI: int = ..., SubT: BFN = ..., UCID: int = ..., ClickID: int = ..., ClickMax: int = ..., Inst: int = ...) -> None: ...
    def send_ISP_BTN(self, ReqI: int = ..., UCID: int = ..., ClickID: int = ..., Inst: INST = ..., BStyle: ISB_STYLE = ..., TypeIn: TYPEIN_FLAGS = ..., L: int = ..., T: int = ..., W: int = ..., H: int = ..., Text: str = ...) -> None: ...
    def send_ISP_CPP(self, ReqI: int = ..., Pos: Vec = ..., H: int = ..., P: int = ..., R: int = ..., ViewPLID: int = ..., InGameCam: VIEW = ..., FOV: float = ..., Time: int = ..., Flags: ISS_CPP = ...) -> None: ...
    def send_ISP_HCP(self, ReqI: int = ..., Info: list = ...) -> None: ...
    def send_ISP_IPB(self, ReqI: int = ..., NumB: int = ..., Sp0: int = ..., Sp1: int = ..., Sp2: int = ..., Sp3: int = ..., BanIPs: list = ...) -> None: ...
    def send_ISP_ISI(self, ReqI: int = ..., UDPPort: int = ..., Flags: ISF = ..., InSimVer: int = ..., Prefix: int = ..., Interval: int = ..., Admin: str = ..., IName: str = ...) -> None: ...
    def send_ISP_JRR(self, ReqI: int = ..., PLID: int = ..., UCID: int = ..., JRRAction: JRR = ..., Sp2: int = ..., Sp3: int = ..., StartPos: ObjectInfo = ...) -> None: ...
    def send_ISP_MAL(self, ReqI: int = ..., NumM: int = ..., UCID: int = ..., Flags: int = ..., Sp2: int = ..., Sp3: int = ..., SkinID: list = ...) -> None: ...
    def send_ISP_MOD(self, ReqI: int = ..., Bits16: MOD_BIT = ..., RR: int = ..., Width: int = ..., Height: int = ...) -> None: ...
    def send_ISP_MSL(self, ReqI: int = ..., Sound: SND = ..., Msg: str = ...) -> None: ...
    def send_ISP_MST(self, ReqI: int = ..., Msg: str = ...) -> None: ...
    def send_ISP_MSX(self, ReqI: int = ..., Msg: str = ...) -> None: ...
    def send_ISP_MTC(self, ReqI: int = ..., Sound: SND = ..., UCID: int = ..., PLID: int = ..., Sp2: int = ..., Sp3: int = ..., Text: str = ...) -> None: ...
    def send_ISP_OCO(self, ReqI: int = ..., OCOAction: OCO = ..., Index: AXO_INDEX = ..., Identifier: int = ..., Data: int = ...) -> None: ...
    def send_ISP_PLC(self, ReqI: int = ..., UCID: int = ..., Sp1: int = ..., Sp2: int = ..., Sp3: int = ..., Cars: CARS = ...) -> None: ...
    def send_ISP_PLH(self, ReqI: int = ..., NumP: int = ..., HCaps: list = ...) -> None: ...
    def send_ISP_REO(self, ReqI: int = ..., NumP: int = ..., PLID: tuple = ...) -> None: ...
    def send_ISP_RIP(self, ReqI: int = ..., Error: RIP = ..., MPR: SMPR = ..., Paused: int = ..., Options: RIPOPT = ..., Sp3: int = ..., CTime: int = ..., TTime: int = ..., RName: str = ...) -> None: ...
    def send_ISP_SCC(self, ReqI: int = ..., ViewPLID: int = ..., InGameCam: VIEW = ..., Sp2: int = ..., Sp3: int = ...) -> None: ...
    def send_ISP_SCH(self, ReqI: int = ..., CharB: CHARS = ..., Flags: SCH_FLAGS = ..., Spare2: int = ..., Spare3: int = ...) -> None: ...
    def send_ISP_SFP(self, ReqI: int = ..., Flag: ISS_SFP = ..., OffOn: OFFON = ..., Sp3: int = ...) -> None: ...
    def send_ISP_SMALL(self, ReqI: int = ..., SubT: SMALL = ..., UVal: int = ...) -> None: ...
    def send_ISP_SSH(self, ReqI: int = ..., Error: SSH = ..., Sp0: int = ..., Sp1: int = ..., Sp2: int = ..., Sp3: int = ..., Name: str = ...) -> None: ...
    def send_ISP_TINY(self, ReqI: int = ..., SubT: TINY = ...) -> None: ...
    def send_ISP_TTC(self, ReqI: int = ..., SubT: TTC = ..., UCID: int = ..., B1: int = ..., B2: int = ..., B3: int = ...) -> None: ...
