"""
Type hints stub para InSimClient - Proporciona autocompletado
"""
from typing import List, Optional, Any
import logging
import queue
import threading
from .insim_transport import InSimTransport
from .packets import ISP_ISI
from .insim_enums import OSO

class InSimClient:
    logger: logging.Logger
    config: dict
    name: str
    running: bool
    connected: bool
    isi: ISP_ISI
    apps: List[Any]
    transport: InSimTransport
    outsim_opts: OSO

    def __init__(self, config: Optional[dict] = None, name: str = "DeepInSim",
                 transport: Optional[InSimTransport] = None) -> None: ...
    def register(self, app: Any) -> Any: ...
    def send(self, packet: Any) -> None: ...

    # Ciclo de vida (hooks)
    def on_connect(self) -> None: ...
    def on_disconnect(self) -> None: ...
    def on_reconnect(self) -> None: ...
    def on_tick(self) -> None: ...
    def on_packet_received(self, packet: Any) -> None: ...

    # Métodos internos
    def _on_raw_bytes(self, data: bytes) -> None: ...
    def _dispatch_packet(self, packet: Any) -> None: ...
    def _dispatch_lifecycle(self, event_name: str, isolate: bool = False) -> None: ...
    @property
    def _fail_fast(self) -> bool: ...
    def _start_dispatch_worker(self) -> None: ...
    def _stop_dispatch_worker(self) -> None: ...
    def _dispatch_loop(self) -> None: ...
    def set_isi_packet(self) -> None: ...
    def set_outsim(self) -> None: ...

    def start(self) -> None: ...
    def stop(self) -> None: ...
