"""
Type hints stub para InSimClient - Proporciona autocompletado
"""
from typing import Dict, List, Optional, Any
import logging
from config.settings import get_config
from .packets import ISP_ISI

class InSimClient:
    # El logger es proporcionado en tiempo de ejecución por InSimClient.__init__
    # y declarado aquí para que los IDEs lo reconozcan incluso sin imports
    logger: logging.Logger
    config: dict
    name: str
    running: bool
    isi: ISP_ISI
    isi_prefix: str
    use_thread_pool: bool
    modules: List[Any]
    
    def __init__(self, config: Optional[dict] = None, name: str = "DeepInSim") -> None: ...
    def register_module(self, module_class: type, **kwargs: Any) -> Any: ...
    
    # Ciclo de vida (hooks)
    def on_connect(self) -> None: ...
    def on_first(self) -> None: ...
    def on_disconnect(self) -> None: ...
    def on_packet_received(self, packet: Any) -> None: ...
    
    # Métodos internos
    def _handle_heartbeat(self, packet: Any) -> bool: ...
    def _dispatch_packet(self, packet: Any) -> None: ...
    def set_isi_packet(self) -> None: ...
    def set_oso_opts(self) -> None: ...
    
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
